export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const GET_SINGLE_PRODUCT_BEGIN = "GET_SINGLE_PRODUCT_BEGIN";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR";

//actions for filtering products
export const GET_ALL_PRODUCTS_FOR_FILTER_BEGIN =
  " GET_ALL_PRODUCTS_FOR_FILTER_BEGIN";
export const GET_ALL_PRODUCTS_FOR_FILTER_SUCCESS =
  "GET_ALL_PRODUCTS_FOR_FILTER_SUCCESS";
export const GET_ALL_PRODUCTS_FOR_FILTER_ERROR =
  "GET_ALL_PRODUCTS_FOR_FILTER_ERROR ";

export const UPDATE_SORT_VALUE = "UPDATE_SORT_VALUE";
export const SORT_PRODUCTS_BY = "SORT_PRODUCTS_BY";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";

//cartcontext actions

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const TOGGLE_CART_ITEM_AMOUNT = "TOGGLE_CART_ITEM_AMOUNT";
export const CLEAR_CART = "CLEAR_CART";
export const COUNT_CART_TOTALS = "COUNT_CART_TOTALS";

// For modal

export const SET_MODAL_TO_CLOSE = " SET_MODAL_TO_CLOSE";
export const SET_MODAL_TO_OPEN = " SET_MODAL_TO_OPEN";

//ALERT

export const SHOW_ALERT = "SHOW_ALERT";
export const CLOSE_ALERT = "CLOSE_ALERT";

//ACRT ITEM INCRE DECRES

export const INCREASE_AMOUNT_CART_ITEM = "INCREASE_AMOUNT_CART_ITEM}";
export const DECREASE_AMOUNT_CART_ITEM = "DECREASE_AMOUNT_CART_ITEM}";

//for  shipping

export const CHANGE_SHIPPING_VALUE = "CHANGE_SHIPPING_VALUE";
